# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Jupyterbook template
author: The Copernicus Climate Change Service (C3S), entrusted to ECMWF (European Centre for Medium-Range Weather Forecasts)

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/ecmwf-training/jupyter-template  # Online location of your book
  branch: develop  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_css: ["_static/custom.css"]
  
launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  colab_url: "https://colab.research.google.com"  # The URL for Google Colab (e.g., https://colab.research.google.com)
  # kaggle_url: "https://www.kaggle.com/kernels/new"  # The URL for Kaggle (e.g., https://www.kaggle.com/kernels/new)
  deepnote_url: "https://deepnote.com"  # The URL for Deepnote (e.g., https://deepnote.com)
  jupyterhub_url: "https://jupyterhub5-test.ecmwf.int"

exclude_patterns:
  - developer/*